hmrc/p800-refunds-frontend

README.md
build.sbt
project/SbtCommands.scala
project/SbtUpdatesSettings.scala
project/ScalaCompilerFlags.scala
project/StrictBuilding.scala
project/WartRemoverSettings.scala

[PP][OPS-9763] strict building

---

project/SbtCommands.scala

[PP][OPS-11157] fix relax

---

conf/application.conf

[PP][OPS-11157] reconfigure urls as discussed

---

app/controllers/CheckYourReferenceController.scala
app/controllers/DoYouWantToSignInController.scala
app/controllers/DoYouWantYourRefundViaBankTransferController.scala
app/controllers/EnterP800ReferenceController.scala
app/controllers/JourneyRouter.scala
app/controllers/RequestReceivedController.scala
app/controllers/YourChequeWillBePostedToYouController.scala
app/views/chequejourney/YourChequeWillBePostedToYouPage.scala.html
conf/app.routes
project/AppDependencies.scala
project/SbtUpdatesSettings.scala
test/pagespecs/ChequeRequestReceivedPageSpec.scala
test/pagespecs/pagesupport/Page.scala

[PP][ops-11309] final page back button

---

app/language/Messages.scala

- had discussion with Jess and this link should stay in same tab
- will fix failing acceptance tests

[DCB][no-ticket] make contact HMRC link stay in same tab

---

app/language/Messages.scala
app/models/forms/WhatIsYourFullNameForm.scala
conf/app.routes
project/AppDependencies.scala
test/pagespecs/WhatIsYourFullNamePageSpec.scala
test/pagespecs/pages/WhatIsYourDateOfBirthPage.scala
test/pagespecs/pages/WhatIsYourFullNamePage.scala
test/pagespecs/pages/WhatIsYourNationalInsuranceNumberPage.scala

Removed /we-need-to-confirm-your-identity route prefix

[MO][OPS-11153] Fix validation errors, amend routes

---

app/controllers/CheckYourAnswersController.scala

- making table not use headers
- adding visually hidden text so screenreaders can understand change links

[DCB][OPS-11181] update check answers accessibility

---

app/controllers/CheckYourAnswersController.scala
app/controllers/NoMoreAttemptsLeftToConfirmYourIdentityController.scala
app/language/Messages.scala
app/views/Views.scala
app/views/identityverification/NoMoreAttemptsLeftToConfirmYourIdentityPage.scala.html
conf/app.routes
test/pagespecs/NoMoreAttemptsLeftToConfirmYourIdentityPageSpec.scala
test/pagespecs/pages/NoMoreAttemptsLeftToConfirmYourIdentityPage.scala
test/pagespecs/pagesupport/Pages.scala

[PP][OPS-11538] no attempts left page

---

app/language/Messages.scala
app/models/forms/PtaOrBankTransferForm.scala
project/AppDependencies.scala
test/pagespecs/ChooseAnotherWayToReceiveYourRefundPageForChequeJourneySpec.scala

[PP][OPS-11524] error content change

---

app/views/DoYouWantToSignInPage.scala.html
test/pagespecs/pages/DoYouWantToSignInPage.scala

- quick fix for missing error title on the "do you want to sign in" page

[DCB][OPS-11503] update error title on sign in page

---

app/assets/stylesheets/application.scss
app/views/GiveYourPermissionPage.scala.html

Move form outside the button group

[TP][OPS-11680]

---

app/controllers/ThereIsAProblemController.scala
app/controllers/YouCannotConfirmYourSecurityDetailsYetController.scala
app/language/Messages.scala
app/views/ThereIsAProblem.scala.html
app/views/Views.scala
conf/app.routes
test/pagespecs/ThereIsAProblemSpec.scala
test/pagespecs/pages/ThereIsAProblemPage.scala
test/pagespecs/pagesupport/Pages.scala

- and correct controller name from OPS-11525

[TP][OPS-11685] - add basic page functionality with tests

---

app/controllers/CheckYourAnswersController.scala
app/controllers/EnterTheNameOfYourBankController.scala
app/controllers/EnterYourDateOfBirthController.scala
app/controllers/EnterYourNationalInsuranceNumberController.scala
app/controllers/EnterYourP800ReferenceController.scala
app/controllers/GiveYourPermissionController.scala
app/models/journeymodels/HasFinished.scala
app/models/journeymodels/IsChanging.scala
app/models/journeymodels/Journey.scala
app/services/JourneyFactory.scala
test/testdata/TdJourney.scala

[PP][ops-11605] reset API calls upon changes in dependant fields

---

app/nps/NpsConnector.scala
test/nps/models/NpsConnectorSpec.scala
test/nps/models/P800ReferenceCheckResultFailuresTest.scala

[PP][ops-11605] fix handling 422 responses

---

app/action/Actions.scala
app/config/AppConfig.scala
app/controllers/CheckYourAnswersController.scala
app/controllers/RequestReceivedController.scala
app/controllers/testonly/TestOnlyController.scala
app/models/attemptmodels/AttemptInfo.scala
app/models/journeymodels/HasFinished.scala
app/models/journeymodels/Journey.scala
app/nps/NpsConfig.scala
app/nps/ReferenceCheckConnector.scala
app/nps/TraceIndividualConnector.scala
app/nps/models/TraceIndividualRequest.scala
app/nps/models/TraceIndividualResponse.scala
app/services/FailedVerificationAttemptService.scala
app/services/JourneyFactory.scala
project/AppDependencies.scala
test/nps/models/ReferenceCheckConnectorSpec.scala
test/pagespecs/CheckYourAnswersSpec.scala
test/pagespecs/ChooseAnotherWayToReceiveYourRefundPageForBankTransferJourneySpec.scala
test/pagespecs/WeHaveConfirmedYourIdentityPageSpec.scala
test/testdata/TdBase.scala
test/testdata/TdJourney.scala
test/testsupport/stubs/EcospendStub.scala
test/testsupport/stubs/NpsTraceIndividualStub.scala
test/testsupport/stubs/WireMockHelpers.scala

[PP][ops-11607] call trace individual API

---

project/AppDependencies.scala

[PP][ops-11605] dependency

---

app/nps/NpsErrorCodes.scala
app/nps/ReferenceCheckConnector.scala
test/nps/NpsErrorCodesSpec.scala
test/nps/models/ReferenceCheckConnectorSpec.scala
test/testsupport/stubs/NpsIssuePayableOrderStub.scala
test/testsupport/stubs/NpsReferenceCheckStub.scala

[PP][ops-11768] align NPS Error codes with documentation

---

project/AppDependencies.scala

[PP][OPS-11451] fix problem running tests from intellij after upgrade to play-3.0

---

app/assets/javascripts/verifying-bank-refresh.js
app/assets/stylesheets/application.scss
app/connectors/P800RefundsExternalApiConnector.scala
app/controllers/WeAreVerifyingYourBankAccountController.scala
app/models/forms/testonly/WebhookSimulationForm.scala
app/models/journeymodels/Journey.scala
app/models/p800externalapi/EventValue.scala
app/services/JourneyFactory.scala
app/views/WeAreVerifyingYourBankAccountPage.scala.html
app/views/testonly/WebhookNotificationSimulationPage.scala.html
conf/app.routes
project/AppDependencies.scala
project/SbtUpdatesSettings.scala
project/plugins.sbt
test/models/journeymodels/JourneySpec.scala
test/pagespecs/GiveYourPermissionPageSpec.scala
test/pagespecs/VerifyBankAccountPageSpec.scala
test/pagespecs/pagesupport/Pages.scala
test/testdata/TdBase.scala
test/testdata/TdJourney.scala
test/testsupport/ItSpec.scala
test/testsupport/stubs/EcospendStub.scala
test/testsupport/stubs/NpsIssuePayableOrderStub.scala
test/testsupport/stubs/NpsReferenceCheckStub.scala
test/testsupport/stubs/NpsTraceIndividualStub.scala
test/testsupport/stubs/P800RefundsExternalApiStub.scala
test/testsupport/stubs/WireMockHelpers.scala

- call /is-valid endpoint
- update tests
- javascript refresh on verifying bank page

[JB][OPS-11614]

---

app/connectors/EcospendConnector.scala
app/connectors/P800RefundsExternalApiConnector.scala
app/controllers/WeAreVerifyingYourBankAccountController.scala
app/models/ecospend/consent/BankConsentResponse.scala
app/models/ecospend/consent/ConsentId.scala
app/views/WeAreVerifyingYourBankAccountPage.scala.html
build.sbt
conf/app.routes
test/pagespecs/GiveYourPermissionPageSpec.scala
test/pagespecs/VerifyBankAccountPageSpec.scala
test/pagespecs/pages/VerifyBankAccountPage.scala
test/testdata/TdBase.scala
test/testsupport/stubs/EcospendStub.scala
test/testsupport/stubs/P800RefundsExternalApiStub.scala

[PP][OPS-11743] ConsentId type (preliminary changes to EDH API)

---

app/config/AppConfig.scala
app/connectors/DateCalculatorConnector.scala
app/controllers/RequestReceivedController.scala
app/language/Messages.scala
app/models/datecalculator/DateCalculatorRequest.scala
app/models/datecalculator/DateCalculatorResponse.scala
app/models/datecalculator/Region.scala
app/services/DateCalculatorService.scala
app/views/BankTransferRequestReceivedPage.scala.html
conf/application.conf
test/pagespecs/RequestReceivedPageSpec.scala
test/pagespecs/VerifyBankAccountPageSpec.scala
test/pagespecs/pages/RequestReceivedPage.scala
test/testsupport/ItSpec.scala
test/testsupport/stubs/DateCalculatorStub.scala

- update request receieved pages so the dates are correct (not static)
- integrate with the date-calculator service

[JB][OPS-11177]

---

app/controllers/WeAreVerifyingYourBankAccountController.scala
app/models/ecospend/account/BankAccountIdentification.scala
app/nps/IssuePayableOrderConnector.scala
test/models/ecospend/account/BankAccountIdentificationSpec.scala
test/testdata/TdEdh.scala

[PP][OPS-11743] bug fixes for account number and sort code

---

app/nps/models/ValidateP800ReferenceFailures.scala
project/AppDependencies.scala
test/nps/models/ValidateP800ReferenceFailuresTest.scala
test/pagespecs/EnterYourP800ReferencePageSpec.scala
test/specs/BankAccountSummaryResponseSpec.scala

[PP][OPS-12117] selenium update and renamings

---

app/connectors/P800RefundsBackendConnector.scala
app/controllers/CheckYourAnswersController.scala
app/controllers/EnterYourP800ReferenceController.scala
app/controllers/WeAreVerifyingYourBankAccountController.scala
app/models/P800Reference.scala
app/models/UserEnteredP800Reference.scala
app/models/forms/EnterP800ReferenceForm.scala
app/models/journeymodels/Journey.scala
app/views/EnterP800ReferencePage.scala.html
test/pagespecs/CheckYourAnswersSpec.scala
test/pagespecs/EnterYourP800ReferencePageSpec.scala
test/pagespecs/IsYourAddressUpToDatePageSpec.scala
test/pagespecs/RequestReceivedPageSpec.scala
test/pagespecs/ThereIsAProblemSpec.scala
test/pagespecs/WeCannotConfirmYourIdentityPageSpec.scala
test/pagespecs/WhatIsYourDateOfBirthPageSpec.scala
test/pagespecs/pages/CheckYourAnswersPage.scala
test/testdata/TdBase.scala
test/testdata/TdEdh.scala
test/testdata/TdJourney.scala
test/testsupport/stubs/NpsIssuePayableOrderStub.scala
test/testsupport/stubs/VerifyP800ReferenceStub.scala

[PP][OPS-12139] Giving P800Reference and UserEnteredP800Reference dedicated types

---

app/controllers/VerifyingYourBankAccountController.scala
app/models/audit/ValidateUserDetails.scala
app/nps/models/MakeBacsRepaymentRequest.scala
app/nps/models/SuspendOverpaymentRequest.scala
app/nps/models/ValidateReferenceResult.scala
test/testdata/TdBase.scala

[PP][OPS-12156] Make reconciliationIdentifier, taxDistrictNumber, payeNumber optional

---

app/crypto/Crypto.scala
app/crypto/JourneyCrypto.scala
app/services/JourneyService.scala
conf/application.conf
project/AppDependencies.scala
test/crypto/JourneyCryptoSpec.scala
test/testsupport/ItSpec.scala

[PP][OPS-11633] encrypt PII in the journey

---

test/testsupport/ItSpec.scala
test/testsupport/stubs/AuditConnectorStub.scala

[PP][OPS-11839] stubs for implicit events so we're not flooded with error messages in tests

---

app/config/AppConfig.scala
app/controllers/TimeoutController.scala
app/language/Messages.scala
app/views/TimeoutPage.scala.html
app/views/templates/Layout.scala.html
conf/app.routes
conf/application.conf
test/pagespecs/TimeoutSpec.scala
test/pagespecs/pages/TimeoutPage.scala
test/pagespecs/pagesupport/Pages.scala

The quick way to test the timeout is adding the following to application.conf
```
session.timeoutSeconds = 40
hmrc-timeout-dialog.defaultCountdownInSeconds = 20
```

[UD][OPS-11641] Implemented session timeout

---

app/controllers/VerifyingYourBankAccountController.scala
test/pagespecs/VerifyingYourBankAccountPageSpec.scala

Correctly report a HMRC fraud check failure

[MO][OPS-12140] Fix BankClaimAttemptMade audit bug

---

app/crypto/AttemptInfoCrypto.scala
app/repository/FailedVerificationAttemptRepo.scala
app/services/FailedVerificationAttemptService.scala
test/crypto/AttemptInfoCryptoSpec.scala
test/crypto/JourneyCryptoSpec.scala
test/testsupport/ItSpec.scala

[PP][OPS-11735] encrypt ip address in mongo

---

README.md

[PP][OPS-9748] improve readme

---

README.md

[PP][OPS-9748] document testing approach

---

app/assets/javascripts/verifying-bank-refresh.js

[PP][OPS-12268] refresh page each 5 seconds

---

app/controllers/VerifyingYourBankAccountController.scala
app/models/journeymodels/Journey.scala
app/models/namematching/NameMatchingResult.scala
app/services/AuditService.scala
app/services/JourneyFactory.scala
project/AppDependencies.scala
test/pagespecs/VerifyingYourBankAccountPageSpec.scala
test/testdata/TdJourney.scala
test/testsupport/stubs/AuditConnectorStub.scala

[MO][OPS-12226] Run name matching only once

---

app/controllers/VerifyingYourBankAccountController.scala
app/models/audit/BankClaimAttempt.scala
app/models/audit/NameMatchingAudit.scala
app/services/GetBankDetailsRiskResultService.scala
app/services/NameMatchingService.scala
test/pagespecs/VerifyingYourBankAccountPageSpec.scala
test/services/NameMatchingServiceSpec.scala
test/testdata/TdAudit.scala
test/testsupport/stubs/EcospendStub.scala

- FuzzyNameMatchingEvent audit add ChosenBank
- Trigger BankClaimAttemptMade audit event on ecospend Account Summary failure

[MO][OPS-12361] Audit event fixes
